### ISSUE TITLE
[Feature] add Page button reload

### ISSUE THREAD

**Issue by RSS1102** [bvaughn/fish-adventure#1]
Haha, it's a pretty good little game.

Can it add a button on the finished page to initiate reload?
It seems a bit troublesome to refresh using a browser.

**Comment by bvaughn** [comment]
I might add something like that at some point. I didn't really intend to make it an actual "game" so much as I just wanted to experiment with how I might build something like this. I haven't done much game programming before and so I just wanted to pick a very small problem to experiment with. :)

**Comment by bvaughn** [comment]
I added re-start button to the end game state.
