### ISSUE TITLE
its cool how to play haha.??

### ISSUE THREAD

**Issue by sujjeee** [bvaughn/fish-adventure#2]

**Comment by bvaughn** [comment]
Haha, yeah I guess it doesn't make much sense (particularly if you haven't played Stardew Valley before). But you "fish" by clicking the screen. While the pointer is down, the "reel" (the green bar) will go up and while the pointer is up the "reel" will go down. You try to keep the reel where the fish is, until the progress meter on the right fills up fully. :)
